module Restaurant {
    struct OrderStatus {
        string customerName;
        long chickenQuantity;
        long colaQuantity;
        double totalCost;
    };

    exception InvalidQuantity {
        string message;
    };

    interface RestaurantManager {
        OrderStatus[] getCurrentOrders();
    };

    interface RestaurantCustomer {
        string[] getMenu();
        string placeOrder(in string customerName, in long chickenQuantity, in long colaQuantity) raises (InvalidQuantity);
        OrderStatus getOrderStatus(in string customerName);
    };
};
